TITLES = [
    "🧠 Explained in 60 Seconds! #shorts",
    "🤯 You'll Finally Understand This! #shorts",
    "⚡ The Truth Explained Fast! #shorts",
    "📚 Learn Something New Today! #shorts",
    "💡 Explained Simply! #shorts",
     "🎬 Movie Explained In 60 Seconds! #shorts",
    "🤯 You Won't Believe This Movie Ending! #shorts",
    "🍿 Movie Recap In One Minute! #shorts",
    "😱 The Plot Twist Explained! #shorts",
    "🎥 Ending Explained Simply! #shorts",
    "🔥 Best Movie Twist Ever! #shorts",
    "💡 Hidden Movie Details Revealed! #shorts",
    "👀 You Missed This Movie Secret! #shorts",
    "🎞️ Full Movie Story In 60 Seconds! #shorts",
    "⚡ Movie Explained Fast! #shorts",
    "🧠 The Real Meaning Behind The Ending! #shorts",
    "🎭 Movie Story Explained! #shorts",
    "🍿 Must-Watch Movie Recap! #shorts",
    "🎬 One Minute Movie Breakdown! #shorts",
    "😮 Movie Facts You Didn't Know! #shorts",
    "💥 The Craziest Movie Scene Explained! #shorts",
    "🎥 Movie Ending You Didn't Understand! #shorts",
    "🚀 Sci-Fi Movie Explained! #shorts",
    "👻 Horror Movie Explained! #shorts",
    "❤️ Romantic Movie Recap! #shorts",
    "🔫 Action Movie Explained! #shorts",
    "🕵️ Mystery Movie Breakdown! #shorts",
    "🎬 Hollywood Movie Explained! #shorts",
    "🌏 Best International Movie Recap! #shorts",
    "🎞️ Movie Plot In One Minute! #shorts",
    "⚠️ Spoiler Alert! Amazing Ending! #shorts",
    "🤩 This Movie Will Blow Your Mind! #shorts",
    "💯 Complete Movie Story Explained! #shorts",
    "🎥 The Ending Changes Everything! #shorts",
    "🍿 Best Thriller Explained! #shorts",
    "🧩 Every Clue Explained! #shorts",
    "🎬 Watch This Before The Movie! #shorts",
    "😲 Movie Ending Revealed! #shorts",
    "💡 The Hidden Meaning Of This Movie! #shorts",
    "🎭 One Minute Movie Review! #shorts",
    "🚨 Most Confusing Movie Explained! #shorts",
    "🎬 Movie Story You Can't Miss! #shorts",
    "🔥 Blockbuster Movie Recap! #shorts",
    "🤖 AI Movie Explained! #shorts",
    "👽 Alien Movie Explained! #shorts",
    "🧟 Zombie Movie Explained! #shorts",
    "🦸 Superhero Movie Explained! #shorts",
    "⚔️ Fantasy Movie Explained! #shorts",
    "🌌 Space Movie Explained! #shorts",
    "🏆 Award-Winning Movie Explained! #shorts",
    "🎥 Everything Explained In 60 Seconds! #shorts",
    "🍿 Best Movie Story Today! #shorts",
    "💥 One Minute Cinema Recap! #shorts",
    "🎬 Quick Movie Explain! #shorts",
    "🚀 Movie Explained Like Never Before! #shorts"
]