TITLES = [
    "📖 This Story Will Change Your Life! #shorts",
    "😱 You Won't Believe This True Story! #shorts",
    "💡 The Most Inspiring Story Ever! #shorts",
    "❤️ A Story Everyone Should Hear! #shorts",
    "🔥 The Ending Will Surprise You! #shorts",
    "❤️ Every Person Should Hear This Story! #shorts",
    "🔥 The Ending Is Unexpected! #shorts",
    "💡 A Story That Teaches Success! #shorts",
    "🌍 Based On A True Story! #shorts",
    "😭 The Most Emotional Story Ever! #shorts",
    "🧠 One Minute, One Powerful Lesson! #shorts",
    "✨ This Story Will Inspire You! #shorts",
    "💪 Never Give Up After Watching This! #shorts",
    "📚 Short Story With A Big Message! #shorts",
    "🌟 The Story Everyone Is Talking About! #shorts",
    "😮 Wait Until The Ending! #shorts",
    "💥 One Minute Motivation! #shorts",
    "🎯 A Story Worth Sharing! #shorts",
    "❤️ This Will Touch Your Heart! #shorts",
    "📖 Hidden Life Lesson! #shorts",
    "🤯 The Truth Behind This Story! #shorts",
    "🔥 Watch Till The End! #shorts",
    "🚀 Success Starts Here! #shorts",
    "💭 Think Before You Skip! #shorts",
    "🌈 A Beautiful Story! #shorts",
    "😢 Emotional Ending! #shorts",
    "🏆 Learn From This Story! #shorts",
    "📜 Story With A Twist! #shorts",
    "💎 Valuable Lesson In 60 Seconds! #shorts",
    "⭐ This Story Will Stay With You! #shorts",
    "🌅 Life-Changing Story! #shorts",
    "🤍 Kindness Always Wins! #shorts",
    "⚡ One Minute Inspiration! #shorts",
    "🎥 Amazing Story Explained! #shorts",
    "💯 Real Story, Real Lesson! #shorts",
    "🔥 Story You Can't Ignore! #shorts",
    "📖 Inspirational Journey! #shorts",
    "😲 Unexpected Ending! #shorts",
    "🌟 Learn Something New! #shorts",
    "🎯 Powerful Life Advice! #shorts",
    "💡 Story With Deep Meaning! #shorts",
    "❤️ Worth Watching! #shorts",
    "🚀 Believe In Yourself! #shorts",
    "✨ Inspirational Moment! #shorts",
    "🧠 Smart People Understand This! #shorts",
    "🌍 A Story For Everyone! #shorts",
    "💪 Keep Moving Forward! #shorts",
    "📚 Never Forget This Lesson! #shorts",
    "🎬 True Inspiration! #shorts",
    "🤩 Incredible Story! #shorts",
    "🔥 The Best Story Today! #shorts",
    "💖 Pure Motivation! #shorts",
    "🏅 Story Of Success! #shorts"

]