TITLES = [
    "🎨 Best Cartoon Moment! #shorts",
    "😂 Cartoon Fun in 60 Seconds! #shorts",
    "🌈 Kids' Favorite Cartoon! #shorts",
    "🎬 Amazing Cartoon Clip! #shorts",
    "😄 Cartoon Comedy Time! #shorts",
    
    "😂 Funniest Cartoon Moment! #shorts",
    "🎬 Cartoon Facts You Didn't Know! #shorts",
    "🤣 This Cartoon Scene Is Crazy! #shorts",
    "🎨 Amazing Animation Secret! #shorts",
    "🤩 Cartoon Lovers Must Watch! #shorts",
    "🎨 The Cutest Cartoon Story Ever! #shorts",
    "😂 Funniest Cartoon Moment! #shorts",
    "🐻 A Cartoon Story With A Twist! #shorts",
    "🌈 Magical Cartoon Adventure! #shorts",
    "✨ Cartoon Story In 60 Seconds! #shorts",
    "🐱 The Smartest Cartoon Cat! #shorts",
    "🐶 A Cartoon Dog's Big Adventure! #shorts",
    "🦊 The Clever Fox Story! #shorts",
    "🐰 Cute Bunny's Amazing Journey! #shorts",
    "🦁 The Brave Lion's Story! #shorts",
    "🐼 The Panda's Secret Mission! #shorts",
    "🐸 The Frog Who Saved Everyone! #shorts",
    "🦄 Magical Cartoon World! #shorts",
    "🐧 The Penguin's Funny Day! #shorts",
    "🐯 The Tiger's Biggest Challenge! #shorts",
    "🎬 Best Cartoon Animation! #shorts",
    "🤣 This Cartoon Will Make You Laugh! #shorts",
    "🌟 Cartoon Heroes In Action! #shorts",
    "🎭 The Most Emotional Cartoon Story! #shorts",
    "🍿 Cartoon Adventure You Can't Miss! #shorts",
    "🐻 Friendship Wins Every Time! #shorts",
    "💖 Heartwarming Cartoon Story! #shorts",
    "🎈 Cartoon Fun In One Minute! #shorts",
    "🚀 Amazing Cartoon Journey! #shorts",
    "🌍 Cartoon Story With A Life Lesson! #shorts",
    "🎉 Cartoon Surprise Ending! #shorts",
    "😲 Wait For The Cartoon Twist! #shorts",
    "🧸 Cute Cartoon Moments! #shorts",
    "🐥 The Little Bird's Big Dream! #shorts",
    "🐢 Slow But Smart! #shorts",
    "🦉 Wise Owl's Great Advice! #shorts",
    "🌸 Cartoon Story For Everyone! #shorts",
    "🍭 Sweet Cartoon Adventure! #shorts",
    "🏰 Cartoon Fairy Tale! #shorts",
    "🐲 Friendly Dragon Story! #shorts",
    "🧙 Cartoon Magic Explained! #shorts",
    "🎨 Beautiful Cartoon Animation! #shorts",
    "🎬 Best Cartoon Scene Today! #shorts",
    "💡 Cartoon Story With A Message! #shorts",
    "🐾 Cute Animal Cartoon Story! #shorts",
    "🤩 You'll Love This Cartoon! #shorts",
    "❤️ The Happiest Cartoon Ending! #shorts",
    "🌟 Cartoon Story You Must Watch! #shorts",
    "🎁 One Minute Cartoon Fun! #shorts",
    "😊 Cartoon Adventure Of The Day! #shorts",
    "🎭 Cartoon Tale With A Twist! #shorts",
    "✨ Family-Friendly Cartoon Story! #shorts",
    "🎈 Cartoon Magic In 60 Seconds! #shorts",
    "🌈 Every Cartoon Fan Will Love This! #shorts",
    "🍿 Best Cartoon Story Today! #shorts"
]
