TITLES = [
    "🎬 Movie Explained in 60 Seconds! #shorts",
    "😱 The Ending Will Shock You! #shorts",
    "🍿 Movie Recap in One Minute! #shorts",
    "🤯 Best Movie Twist Ever! #shorts",
    "🎥 Watch Till The End! #shorts",
    "🎬 Movie Explained In 60 Seconds! #shorts",
    "😱 The Ending Will Shock You! #shorts",
    "🍿 Movie Recap In One Minute! #shorts",
    "🤯 You Missed This Plot Twist! #shorts",
    "🎥 Watch Before Watching The Movie! #shorts",
    "🔥 Best Movie Twist Ever! #shorts",
    "🎭 Movie Ending Explained! #shorts",
    "💀 This Scene Changed Everything! #shorts",
    "😲 Hidden Details You Missed! #shorts",
    "🎬 Movie Story In 60 Seconds! #shorts",
    "🧠 The Truth Behind The Ending! #shorts",
    "🍿 Hollywood Movie Explained! #shorts",
    "🎞️ Movie Plot Explained Fast! #shorts",
    "🤔 Can You Guess The Ending? #shorts",
    "⚡ The Most Unexpected Ending! #shorts",
    "🎥 Movie Explained In One Minute! #shorts",
    "👀 Watch Till The End! #shorts",
    "💥 The Ending Nobody Expected! #shorts",
    "🎬 Movie Summary In 60 Seconds! #shorts",
    "🔥 The Craziest Movie Twist! #shorts",
    "😮 This Movie Is Mind-Blowing! #shorts",
    "🎭 Ending Explained Simply! #shorts",
    "🍿 Must-Watch Movie Recap! #shorts",
    "🎥 One Minute Movie Review! #shorts",
    "🤩 You Need To Watch This Movie! #shorts",
    "🎬 Story Explained In 60 Seconds! #shorts",
    "🕵️ Hidden Meaning Revealed! #shorts",
    "💡 Movie Explained Like Never Before! #shorts",
    "🎞️ Best Movie Scene Explained! #shorts",
    "⚠️ Spoiler Alert! Amazing Ending! #shorts",
    "🎬 One Minute Movie Breakdown! #shorts",
    "😱 The Final Scene Explained! #shorts",
    "🍿 Movie Facts You Didn't Know! #shorts",
    "🎥 This Ending Changes Everything! #shorts",
    "🧩 Every Clue Explained! #shorts",
    "🤯 Mind-Bending Movie Explained! #shorts",
    "🎭 Movie Ending You Didn't Understand! #shorts",
    "🎬 Quick Movie Recap! #shorts",
    "🔥 The Best Thriller Explained! #shorts",
    "👁️ The Secret Behind The Story! #shorts",
    "🍿 Mystery Movie Explained! #shorts",
    "🎥 Horror Movie Explained! #shorts",
    "❤️ Romantic Movie In One Minute! #shorts",
    "🚀 Sci-Fi Movie Explained! #shorts",
    "🦸 Superhero Movie Explained! #shorts",
    "⚔️ Action Movie Recap! #shorts",
    "🎞️ Movie Story You Can't Miss! #shorts",
    "😲 Plot Twist Revealed! #shorts",
    "🎬 One Minute Cinema Recap! #shorts",
    "🍿 Best Movie Recap Channel! #shorts"
]