TITLES = [
    "🌿 Relaxing Nature Lofi 🌙",
    "🎵 Peaceful Lofi Beats 🍃",
    "☁️ Calm Night Lofi Mix",
    "🌧️ Rain & Lofi Vibes",
    "🍂 Study with Nature Lofi",
    
    "🎧 Relax & Study With Lofi! #shorts",
    "🌙 Peaceful Lofi Vibes! #shorts",
    "📚 Best Study Music! #shorts",
    "☕ Chill Beats For Your Day! #shorts",
    "🎶 Calm Your Mind In 60 Seconds! #shorts"
    "🌧️ Rainy Day Lofi Beats! #shorts",
    "✨ Chill Lofi For Your Day! #shorts",
    "💤 Relax Your Mind In 60 Seconds! #shorts",
    "🌌 Calm Night Lofi Mix! #shorts",
    "🎵 Your Daily Dose Of Lofi! #shorts",
    "📖 Study Smarter With Lofi! #shorts",
    "😌 Take A Break With Lofi! #shorts",
    "🌿 Nature Meets Lofi! #shorts",
    "🎹 Beautiful Chill Piano Lofi! #shorts",
    "💙 Lofi Music For Peaceful Moments! #shorts",
    "🚀 Boost Your Focus With Lofi! #shorts",
    "🧠 Deep Focus Lofi Beats! #shorts",
    "🌙 Sleep Better With Lofi! #shorts",
    "☁️ Soft Lofi For Relaxation! #shorts",
    "🎼 Calm Beats For Every Mood! #shorts",
    "📚 Study Session Starts Here! #shorts",
    "🌅 Morning Lofi Energy! #shorts",
    "🌃 Night Study Lofi! #shorts",
    "🎧 Relax, Breathe & Listen! #shorts",
    "💻 Coding With Lofi Beats! #shorts",
    "📖 Reading + Lofi = Perfect Combo! #shorts",
    "🌧️ Cozy Rain & Lofi! #shorts",
    "🎹 Piano Lofi Magic! #shorts",
    "💜 Peaceful Lofi Journey! #shorts",
    "🎶 Lofi To Calm Your Soul! #shorts",
    "🌠 Dreamy Lofi Atmosphere! #shorts",
    "☕ Evening Coffee Lofi! #shorts",
    "🎵 Relaxing Beats For Everyone! #shorts",
    "😴 Wind Down With Lofi! #shorts",
    "🕯️ Cozy Room Lofi Vibes! #shorts",
    "📚 Focus Mode Activated! #shorts",
    "🌊 Ocean Wave Lofi! #shorts",
    "🌸 Beautiful Spring Lofi! #shorts",
    "❄️ Winter Chill Lofi! #shorts",
    "🍂 Autumn Lofi Vibes! #shorts",
    "🎧 Pure Chill Beats! #shorts",
    "🌈 Relax Anywhere With Lofi! #shorts",
    "💡 Better Focus Starts Here! #shorts",
    "🎼 One Minute Of Peace! #shorts",
    "🌙 Quiet Night, Soft Beats! #shorts",
    "📚 Ultimate Study Companion! #shorts",
    "☁️ Escape Into Lofi! #shorts",
    "💤 Calm Music For Better Sleep! #shorts",
    "🎶 Feel The Lofi Vibes! #shorts",
    "✨ Your Favorite Lofi Moment! #shorts"


]