TITLES = [
    "👻 Creepy Story That Will Keep You Awake! #shorts",
    "😱 Horror Story in 60 Seconds! #shorts",
    "💀 Don't Watch This Alone! #shorts",
    "🕯️ The Scariest Story Ever! #shorts",
    "👀 True Horror Story! #shorts",

    "👻 This Horror Story Is Terrifying! #shorts",
    "😱 Don't Watch Alone! #shorts",
    "💀 The Scariest Story Ever! #shorts",
    "🕷️ True Horror In 60 Seconds! #shorts",
    "🌑 The Ending Will Haunt You! #shorts",
     "👻 This Horror Story Will Haunt You! #shorts",
    "😱 Don't Watch This Alone! #shorts",
    "💀 The Scariest Story You'll Hear Today! #shorts",
    "🌑 What Happened That Night? #shorts",
    "🩸 A True Horror Story! #shorts",
    "👁️ Someone Was Watching... #shorts",
    "🚪 Never Open That Door! #shorts",
    "🕯️ The Haunted House Mystery! #shorts",
    "😨 The Ending Will Give You Chills! #shorts",
    "🌙 Midnight Horror Story! #shorts",
    "👻 Paranormal Encounter Explained! #shorts",
    "⚰️ The Cemetery Secret! #shorts",
    "🔪 This Story Gets Dark Fast! #shorts",
    "🧟 The Truth Behind The Legend! #shorts",
    "📖 The Creepiest Story Ever Told! #shorts",
    "🌫️ Something Followed Him Home... #shorts",
    "😈 Evil Lurks In The Dark! #shorts",
    "👣 They Heard Footsteps... #shorts",
    "🏚️ The Abandoned House Horror! #shorts",
    "🩸 A Nightmare Come To Life! #shorts",
    "🕷️ Don't Look Behind You! #shorts",
    "👹 The Monster Was Real! #shorts",
    "🌒 The Last Phone Call... #shorts",
    "📞 A Call From The Unknown! #shorts",
    "🚆 The Ghost Train Mystery! #shorts",
    "🎭 The Mask Nobody Should Wear! #shorts",
    "🧸 The Haunted Doll Story! #shorts",
    "🪞 Never Stare Into This Mirror! #shorts",
    "😵 One Minute Of Pure Terror! #shorts",
    "🩻 The Hospital Horror! #shorts",
    "👁️ The Shadow In The Room! #shorts",
    "🌲 Lost In The Haunted Forest! #shorts",
    "⚠️ This Urban Legend Is Terrifying! #shorts",
    "😰 Based On A Creepy Tale! #shorts",
    "👤 He Wasn't Alone... #shorts",
    "🕸️ The House Had A Secret! #shorts",
    "🔦 They Shouldn't Have Explored It! #shorts",
    "😈 The Demon Never Left! #shorts",
    "🌘 The Night Everything Changed! #shorts",
    "☠️ Beware Of The Darkness! #shorts",
    "📚 Horror Story In 60 Seconds! #shorts",
    "💀 You Won't Forget This Ending! #shorts",
    "👁️ Something Is Watching You... #shorts",
    "🚨 The Truth Is More Terrifying! #shorts",
    "🌑 Enter If You Dare! #shorts",
    "🩸 This Story Isn't For The Weak! #shorts",
    "👻 The Ghost Never Left! #shorts",
    "😨 Can You Survive This Story? #shorts",
    "🌙 Watch With The Lights On! #shorts",
    "💀 The Ending Will Haunt Your Dreams! #shorts"

]